[package]
name = "lagoss-runtime-http"
version = "0.1.0"
edition = "2021"

[dependencies]
v8 = "0.74.3"
http = "1.0"
bytes = "1.5"
anyhow = "1.0.72"
lagoss-runtime-v8-utils = { path = "../runtime_v8_utils" }
